# Generated by Django 3.1.7 on 2021-02-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='location',
        ),
    ]
