# Generated by Django 3.1.7 on 2021-02-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
